//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Routing.Proxy {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="Proxy.ProxyServiceI")]
    public interface ProxyServiceI {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ProxyServiceI/GetContracts", ReplyAction="http://tempuri.org/ProxyServiceI/GetContractsResponse")]
        string GetContracts();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ProxyServiceI/GetContracts", ReplyAction="http://tempuri.org/ProxyServiceI/GetContractsResponse")]
        System.Threading.Tasks.Task<string> GetContractsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ProxyServiceI/GetStations", ReplyAction="http://tempuri.org/ProxyServiceI/GetStationsResponse")]
        string GetStations();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ProxyServiceI/GetStations", ReplyAction="http://tempuri.org/ProxyServiceI/GetStationsResponse")]
        System.Threading.Tasks.Task<string> GetStationsAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ProxyServiceIChannel : Routing.Proxy.ProxyServiceI, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ProxyServiceIClient : System.ServiceModel.ClientBase<Routing.Proxy.ProxyServiceI>, Routing.Proxy.ProxyServiceI {
        
        public ProxyServiceIClient() {
        }
        
        public ProxyServiceIClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ProxyServiceIClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ProxyServiceIClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ProxyServiceIClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetContracts() {
            return base.Channel.GetContracts();
        }
        
        public System.Threading.Tasks.Task<string> GetContractsAsync() {
            return base.Channel.GetContractsAsync();
        }
        
        public string GetStations() {
            return base.Channel.GetStations();
        }
        
        public System.Threading.Tasks.Task<string> GetStationsAsync() {
            return base.Channel.GetStationsAsync();
        }
    }
}
